# Generated by Django 4.2.7 on 2025-10-21 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_school_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('study_year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')])),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('max_students', models.PositiveIntegerField(default=30, help_text='Maximum number of students in this group')),
                ('current_students', models.PositiveIntegerField(default=0, help_text='Current number of enrolled students')),
                ('group_code', models.CharField(blank=True, help_text='Auto-generated group code', max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_groups', to='admin_app.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_groups', to='admin_app.school')),
            ],
            options={
                'db_table': 'academic_groups',
                'unique_together': {('school', 'department', 'group_name', 'study_year', 'semester', 'academic_year')},
            },
        ),
    ]
