# Generated by Django 4.2.7 on 2025-10-22 04:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField()),
                ('nation', models.CharField(choices=[('uzbek', 'Uzbek'), ('russian', 'Russian'), ('tajik', 'Tajik'), ('kazakh', 'Kazakh'), ('kyrgyz', 'Kyrgyz'), ('karakalpak', 'Karakalpak'), ('tatar', 'Tatar'), ('korean', 'Korean'), ('other', 'Other')], default='uzbek', max_length=50)),
                ('passport_series', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=20)),
                ('home_address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20)),
                ('is_from_large_family', models.BooleanField(default=False)),
                ('is_from_low_income_family', models.BooleanField(default=False)),
                ('is_from_troubled_family', models.BooleanField(default=False)),
                ('are_parents_deceased', models.BooleanField(default=False)),
                ('has_disability', models.BooleanField(default=False)),
                ('father_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('father_telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_father_retired', models.BooleanField(default=False)),
                ('is_father_disabled', models.BooleanField(default=False)),
                ('mother_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_mother_retired', models.BooleanField(default=False)),
                ('is_mother_disabled', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admin_app.academicgroup')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
