# Generated by Django 4.2.7 on 2025-10-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_father_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_mother_deceased',
            field=models.BooleanField(default=False),
        ),
    ]
