# Generated by Django 4.2.7 on 2025-10-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_student_is_father_deceased_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_series',
        ),
        migrations.AddField(
            model_name='student',
            name='id_card',
            field=models.CharField(blank=True, help_text='ID Card number (e.g., AD4843147)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='nation',
            field=models.CharField(blank=True, choices=[('uzbek', 'Uzbek'), ('russian', 'Russian'), ('tajik', 'Tajik'), ('kazakh', 'Kazakh'), ('kyrgyz', 'Kyrgyz'), ('karakalpak', 'Karakalpak'), ('tatar', 'Tatar'), ('korean', 'Korean'), ('other', 'Other')], default='uzbek', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
