# Generated by Django 4.2.7 on 2025-10-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_update_student_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, help_text='Password for login', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, help_text='Username for login (uses ID Card)', max_length=20, null=True, unique=True),
        ),
    ]
