# Generated by Django 4.2.7 on 2025-10-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_add_student_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='children_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of children (if married)'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, help_text='Legal guardian full name (if both parents deceased)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone_number',
            field=models.CharField(blank=True, help_text='Guardian phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.CharField(blank=True, help_text="Student's hobbies and interests", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Languages spoken with proficiency level', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='siblings_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of siblings'),
        ),
        migrations.AddField(
            model_name='student',
            name='special_skills',
            field=models.CharField(blank=True, help_text='Special skills and talents', max_length=200, null=True),
        ),
    ]
