# Generated by Django 4.2.7 on 2025-10-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_add_gender_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='are_parents_divorced',
            field=models.BooleanField(default=False, help_text='Check if parents are divorced'),
        ),
    ]
