# Generated by Django 4.2.7 on 2025-11-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_add_parents_divorced_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='agreed_to_code_of_conduct',
            field=models.BooleanField(default=False, help_text='Student has agreed to the Code of Ethical Conduct'),
        ),
        migrations.AddField(
            model_name='student',
            name='code_agreement_date',
            field=models.DateTimeField(blank=True, help_text='Date when student agreed to the code', null=True),
        ),
    ]
